web/router.ex
defmodule Myapp.Router do
  use Myapp.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SetLocale, gettext: Myapp.Gettext, default_locale: "en", cookie_key: "project_locale"
    plug Myapp.CurrentUserPlug

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Myapp do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :dummy
  end

  scope "/:locale", Myapp do
    pipe_through :browser # Use the default browser stack
    
    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    
    resources "/users", UserController do
      resources "/posts", PostController
    end

#   resources "/posts", PostController, only: [:index]
    resources "/posts", PostShowController, only: [:index, :show]
  end  

  # Other scopes may use custom stacks.
  # scope "/api", Myapp do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Myapp.LayoutView do
  use Myapp.Web, :view

  def locale_list do
    Application.get_env(:myapp, :locales)
  end

  def locale_path(conn, lng) do
    conn.path_info
    |> tl
    |> Enum.join("/")
    |> String.replace_prefix("", "/#{lng}/")
  end
  
  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= gettext "Hello Myapp!" %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-left">
           <%= for locale <- locale_list() do %>
            <li><%= link locale, to: locale_path(@conn, locale), class: "btn btn-default btn-xs" %></li>
           <% end %>
          </ul>
          <ul class="nav nav-pills pull-right">
            <li>
            <%= if user = current_user(@conn) do %>
            <%= gettext "Logged in as" %>
            <strong><%= link user.username, to: user_path(@conn, :show, @locale, user.id) %></strong>
            <%= link gettext("Listing posts"), to: user_post_path(@conn, :index, @locale, user.id) %>
            <br>
            <%= link gettext("Log out"), to: session_path(@conn, :delete, @locale, user.id), method: :delete, class: "btn btn-default btn-xs" %>
            <% else %>
            <%= link gettext("Log in"), to: session_path(@conn, :new, @locale), class: "btn btn-default btn-xs" %>
            <% end %>
            </li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>