web/router.ex
defmodule Myapp.Router do
  use Myapp.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SetLocale, gettext: Myapp.Gettext, default_locale: "en", cookie_key: "project_locale"
    plug Myapp.CurrentUserPlug

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Myapp do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :dummy
  end

  scope "/:locale", Myapp do
    pipe_through :browser # Use the default browser stack
    
    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    
    resources "/users", UserController do
      resources "/posts", PostController
    end

#   resources "/posts", PostController, only: [:index]
    resources "/posts", PostShowController, only: [:index, :show]
  end  

  # Other scopes may use custom stacks.
  # scope "/api", Myapp do
  #   pipe_through :api
  # end
end

web/controllers/post_show_controller.ex
defmodule Myapp.PostShowController do
  use Myapp.Web, :controller
  alias Myapp.Post

  def index(conn, _params) do
    posts = Repo.all(from p in Post, limit: 5, order_by: [desc: :inserted_at], preload: [:user])
    render(conn, "index.html", posts: posts)
  end

  def show(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    render(conn, "show.html", post: post)
  end

end

web/views/post_show_view.ex
defmodule Myapp.PostShowView do
  use Myapp.Web, :view
end

web/templates/post_show/index.html.eex
<h2><%= gettext "Listing posts" %></h2>

<table class="table">
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= link post.title, to: post_show_path(@conn, :show, @locale, post) %></td>
    </tr>
    <tr>
      <td><%= post.body %></td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/post_show/show.html.eex
<h2><%= gettext "Show post" %></h2>

<ul>

  <li>
    <strong><%= gettext "Title" %>:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong><%= gettext "Body" %>:</strong>
    <%= @post.body %>
  </li>

</ul>

<span><%= link gettext("Back"), to: post_show_path(@conn, :index, @locale), class: "btn btn-default btn-xs" %></span>